### PR TITLE
fix out of bound error

### PR DESCRIPTION
**Pull request by Spacechild1**
make sure argv is within bounds before dereferencing it.

### CODE REVIEW

**Comment by porres** [comment]
what do you think of also doing this?

"
            if (argc > 1 && (argv+1)->a_type == A_SYMBOL)
                f = atom_getfloat(argv+1);
"

**Comment by porres** [comment]
oops

**Comment by porres** [comment]
if (argc > 1 && (argv+1)->a_type == **A_FLOAT**)
                f = atom_getfloat(argv+1);

**Comment by Spacechild1** [comment]
not necessary. atom_getfloat already does the check and returns 0 if it's not a float (but if it's not a symbol, what else can it be? ;-))

**Comment by porres** [comment]
i dont know, a pointer?

**Comment by Spacechild1** [comment]
sorry, my comment in paranthesis is void. 
only Chuck Norris can type a pointer in Pd.

**Comment by porres** [comment]
> sorry, my comment in paranthesis is void

what do you mean?

**Pull request merged**
