### PR TITLE
html: corrections.

### PR DESCRIPTION
**Pull request by Lucarda**
needed corrections in the code.

### CODE REVIEW

**Comment by Lucarda** [comment]
ping @porres

**Comment by Lucarda** [comment]
Oh i now see that it was not you who did this commit: https://github.com/pure-data/pure-data/commit/f917bd20d8a49bdd38a9af8aa6f179ebb7fc2ad9

I'm closing this as is incomplete anyway. sorry for the noise.

**Comment by porres** [comment]
you can send it to my branch anyway

**Comment by Lucarda** [comment]
Good. i'll try.

will reopen but make it draft until i got it complete.

**Comment by Lucarda** [comment]
@porres this one is ready to go.

**Pull request merged**
