### PR TITLE
paint it black

### PR DESCRIPTION
**Pull request by ben-wes**
@porres: your choice. i'm in. :)

### CODE REVIEW

**Comment by porres** [comment]
> @porres: your choice. i'm in. :)

let's see if @lucarda has something to say... also, this looks like a polishment we can think of later, that also needs to be applied to all the manual. chapter 2 may not be the only place for shortcuts, right?

**Comment by ben-wes** [comment]
didn't find any others with a quick search through all `<code>` blocks. but maybe I missed some.

**Comment by porres** [comment]
> didn't find any others with a quick search through all <code> blocks. but maybe I missed some.

we just added <code> for chapter 2, maybe there is more in other chapters that would also need '<control>' and stuff

**Comment by ben-wes** [comment]
@porres : the formatting in your comment got messed up a bit since these tags also work in the markdown here. :)

... anyway - responding based on speculation of what you might have written: `<code>` tags are used quite often already in x4 and x6* chapters. but i don't see any keyboard shortcuts there; only terminal commands and formatting in the table of x4. so i think, the current state is finished in this concern (no need for more `<kbd>` tags anywhere else).

**Comment by Lucarda** [comment]
for me i would use a softer black: `background-color:#404040;`

but i'm ok on having it as is (jumping more off the screen (at least on Windows.)

just a suggestion.

here shown with `background-color:#404040;`

softerblack

**Comment by porres** [comment]
looks nice indeed

**Comment by ben-wes** [comment]
@Lucarda @porres alright! i added another commit to align the background color with the font color, which is `#3E4349` - and therefore pretty close to `#404040`. also font is now completely white inside and the border a bit brighter as well.

screenshot from windows edge (the funky colors in detail stem from microsoft's cleartype subpixel rendering - so we can ignore that):
image

**Comment by Lucarda** [comment]
it's ok.

:)

**Pull request merged**
