### PR TITLE
add files to makefile.am

### PR DESCRIPTION
**Pull request by Lucarda**
I made this PR for your branch as it's about files in the `doc` folder.

### CODE REVIEW

**Comment by porres** [comment]
please tell me what this is doing, and note there are conflicts now

**Comment by porres** [comment]
can you try again?

**Comment by Lucarda** [comment]
I'll try a new one later. there was an html file that was missing in the list and also there are new .pd files that must get included.

have to leave now but i'm carring a notebook.

**Comment by porres** [comment]
ok, rebase and everything... miller just took my PR

**Pull request closed without merging**
