### PR TITLE
Receive inlet

### PR DESCRIPTION
**Pull request by Spacechild1**
clean up code + don't bind empty symbols

### CODE REVIEW

**Comment by porres** [comment]
Hi, [receive] does bind to empty symbols and always have... I don't think we should change that.

If you create a [send] and [receive] without arguments, they're bound together and you can send messages like that. Anyway, this would change/break the current behaviour, it's not something silly I introduced ;)

**Comment by porres** [comment]
Anyway, I cherry picked the changes and also fixed the help file in a new personal commit. Maybe just delete this now?

thanks

**Comment by Spacechild1** [comment]
cool

**Comment by porres** [comment]
I didn't know how to do that :) - well, it's been over 3 years using github, maybe it's time I read the fucking manual

**Pull request closed without merging**
