### PR TITLE
manual revision: add cursors, static deken install image in ch2

### PR DESCRIPTION
**Pull request by ben-wes**
@porres @lucarda : let me know if these look good to you.

### CODE REVIEW

**Comment by Lucarda** [comment]
looks good. just 2 things:

- i think you have to rebase (i had made changes)
- should we include this step in the deken description ?

dekenstep

**Comment by Lucarda** [comment]
i have to leave for 3hs.

**Comment by ben-wes** [comment]
should be rebased and include new deken image.

**Comment by porres** [comment]
who should 'rebase' and how?

**Comment by ben-wes** [comment]
> who should 'rebase' and how?

misunderstanding, sorry. my branch wasn't including @Lucarda's changes yet. so i had to fetch and rebase. there's nothing left to do (i hope).

**Comment by Lucarda** [comment]
it all seems ok for me.

:)

**Pull request merged**
